message: "Bonjour"

# server configuration
server:
  applicationContextPath: /app
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: src/main/resources/KeyStore.jks
      keyStorePassword: ifVSetMV3LpjwHOocTIGLmQGNm2UWbgY
  adminConnectors:
    - type: http
      port: 8081

# database configuration
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: mohit
  password: Mysql@123
  url: jdbc:mysql://localhost:3306/usermanager
  validationQuery: "/* MyService Health Check */ SELECT 1"

# logger configuration
logging:
  level: INFO
  loggers:
    com.dropapp.app: DEBUG
    org.jdbi.v3: DEBUG

  appenders:
    - type: console
    - type: file
      threshold: INFO
      currentLogFilename: ./logs/dropapp.log
      archivedLogFilenamePattern: ./logs/dropapp-%d{yyyy-mm-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB